// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/finding": {
    params: {};
  };
  "/listing": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/finding" | "/listing";
  };
  "routes/home.jsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/finding.jsx": {
    id: "routes/finding";
    page: "/finding";
  };
  "routes/listing.jsx": {
    id: "routes/listing";
    page: "/listing";
  };
};